package RM;

import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import RM.koneksiDB.con;
import RM.form_login;

/**
 *
 * @author CHERLY CHRYS
 */
public class form_login extends javax.swing.JFrame {

    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabmodel;
    Connection con = (Connection) RM.koneksiDB.getkoneksi();

    public form_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_masuk = new javax.swing.JButton();
        btn_exit = new javax.swing.JButton();
        txt_username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        btn_masuk.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_masuk.setText("SIGN IN");
        btn_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_masukActionPerformed(evt);
            }
        });
        getContentPane().add(btn_masuk);
        btn_masuk.setBounds(440, 600, 130, 60);

        btn_exit.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btn_exit.setText("EXIT");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_exit);
        btn_exit.setBounds(440, 680, 130, 33);

        txt_username.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(txt_username);
        txt_username.setBounds(330, 380, 350, 60);

        password.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        getContentPane().add(password);
        password.setBounds(330, 490, 350, 60);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 450, 150, 40);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Username :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(340, 340, 140, 40);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Exotc350 DmBd BT", 0, 38)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("LOGIN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(410, 280, 180, 50);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 700, 760);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login2.jpg"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(680, 566));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -4, 700, 770);

        setSize(new java.awt.Dimension(697, 763));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_masukActionPerformed
        try {
            st = con.createStatement();
            rs = st.executeQuery("select*from form_login where " + "username='" + txt_username.getText() + "'");

            if (rs.next()) {
                if (password.getText().equals(rs.getString("password"))) {
                    JOptionPane.showMessageDialog(rootPane, "Selamat Datang");
                    new form_pemesanan().setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Password Salah");
//                    user.setText("");
                    password.setText("");
                    password.requestFocus();
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Username Salah");
                txt_username.setText("");
//                pass.setText("");
                txt_username.requestFocus();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btn_masukActionPerformed

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "Apakah anda yakin untuk keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            dispose();
        }
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

 /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_masuk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
